name: Windows

on: [push, pull_request]

jobs:
  vs2019:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Cache vcpkg
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      id: cache-vcpkg
      with:
        path: vcpkg/
        key: vcpkg-x64-windows

    - name: Install Dependencies
      if: ${{ !steps.cache-vcpkg.outputs.cache-hit }}
      shell: pwsh
      run: |
        git clone https://github.com/microsoft/vcpkg
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install
        .\vcpkg install cppgraphqlgen gtest --triplet x64-windows

    - name: Configure
      shell: pwsh
      run: |
        $vcpkgToolchain = Join-Path '.\vcpkg' '.\scripts\buildsystems\vcpkg.cmake' -Resolve

        "CMAKE_TOOLCHAIN_FILE=$vcpkgToolchain" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

    - name: Build
      run: npm install

# The Test step depends on having a 64-bit version of Microsoft Office installed on the machine.
#    - name: Test
#      run: npm test
